Repository Dhruvi-tech/firebase-chat-app, pull requests merged in 2025-08, with the labels that each got.

#29 Fix Auth Error UI
  src/components/Auth.jsx
Labels: GSSoC'25, Level 2

#51 feat: add timestamps to chat messages
  src/components/Chat.jsx
Labels: GSSoC'25, Level 1

#52 solved performance issues
  package-lock.json
  package.json
  src/App.jsx
  src/components/Chat.jsx
Labels: GSSoC'25, Level 3
